version: "2"

services:
  jenkins:
    restart: always
    container_name: "jenkins"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=jenkins.quazarus.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jenkins.quazarus.com
      - LETSENCRYPT_EMAIL=admin@admin.com
    volumes:
      - jenkins_storage:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy

volumes:
  jenkins_storage:
    external:
      name: jenkins_storage
